
_MACRO_ERROR = "MACRO ERROR: "
_MSG_MARKER = ". "

	MAC DASM_MACRO_ERROR
		ECHO _MACRO_ERROR, {#}
		ERR
	ENDM

	MAC DASM_MESSAGE
		ECHO _MSG_MARKER, {#}
	ENDM

	MAC PAGE_CHECK
_PAGE_CHECK = >*
	ENDM

	MAC PAGE_CHECK_END
	IF _PAGE_CHECK != >*
		DASM_MACRO_ERROR "page check fail:", {1}, "spans more than one page"
	ENDIF
	ENDM
