
	mac IDLE_WSYNC_TO_VISIBLE_SCREEN
		NOP
		NOP
		NOP
		NOP
		NOP
		NOP
		NOP
		NOP
		NOP
	endm

	mac IDLE_ONE_COLOR_CYCLE
		NOP
		NOP
	endm

COLOR_COUNTS_PER_SCANLINE = 228
CYCLES_PER_COLOUR_COUNT = 3
CYCLES_PER_SCANLINE = COLOR_COUNTS_PER_SCANLINE / CYCLES_PER_COLOUR_COUNT
VBLANK_KERNEL_TIMER_SET_IN_CYCLES = 5
VBLANK_KERNEL_WAIT_LOOP = 6

; define VBLANK_SCANLINES somewhere in your source

VBLANK_TIMER_VAL = (CYCLES_PER_SCANLINE * VBLANK_SCANLINES - VBLANK_KERNEL_TIMER_SET_IN_CYCLES - VBLANK_KERNEL_WAIT_LOOP) / 64

	mac VSYNC_KERNEL
	VERTICAL_SYNC
	VBLANK_KERNEL_SETUP
	endm

	mac VBLANK_KERNEL_SETUP
	LDA	#VBLANK_TIMER_VAL
	STA TIM64T
	endm

	mac VBLANK_KERNEL_WAIT
vblank_loop
	LDA INTIM
	BNE vblank_loop
	endm
